name: sn_progress_dialog
description: Customizable progress dialog package for Flutter.(Captures the progress value)
version: 2.0.0
homepage: https://github.com/emreesen27/Flutter-Progress-Dialog

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - images/cancel.png
    - images/completed.png
